### ISSUE TITLE
Generate Test Vectors from AFG

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/waci-didcomm#1]
- Lets assume JsonWebSignature2020.
- Pick a use case (like PRC)
- English language description of tests, for both issuance and presentation.
- Define the CM objects (only relevant to issuance)
- Define the PE objects (only relevant to presentation exchange)
- write code in AFG to gather data from the examples, do not attempt AATH until AFG integration is done
- capture the issuance exchange JSON messages
- capture the presentation exchange JSON messages
- save them all to a directory.
- open a pull request here to add examples from the directory to the spec.

**Comment by bumblefudge** [comment]
Discussed on today's call: 
- Brent noticed a BBS type in some of the examples - Rolson fixing and coming back
- A simple readme for each folder explaining which step in the spec each file corresponds to and a super-quick, highlevel "choreography" as Daniel Hardman would say ("if your system consumes 1 & 4, it should produce something like 2, 3 and 5") should meet the "english language" request

**Comment by OR13** [comment]
we did it fam!
