### ISSUE TITLE
Attachment links not working 

### ISSUE THREAD

**Issue by Vaplet** [decentralized-identity/waci-didcomm#23]
Hi,
The links for the presentation exchange attachment formats do not work. 
In the protocol you say that "_dif/presentation-exchange/submission@v1.0_" and "_dif/presentation-exchange/definitions@v1.0_" attachment formats can be used (**first** issue here: It should be only "definition" not "definitions" if you refer to https://github.com/hyperledger/aries-rfcs/blob/main/features/0510-dif-pres-exch-attach/README.md).
But anyway. The links do not work:  https://github.com/decentralized-identity/waci-didcomm/blob/main/0510-dif-pres-exch-attach/README.md#propose-presentation-attachment-format with site result 404. 
So **second** issue, where should I find the documentation ? 
In the url I can see you refer to _Aries 0510_ which I guess is more for DIDComm v1 not for the version 2. I googled it by myself, but I am not sure. Shouldn't the attachement format be in regards to Presentation Exchange 2.0? https://identity.foundation/presentation-exchange/#presentation-request

**Comment by OR13** [comment]
There are 2 reported issues here.

1. attachment format is not defined / 404.
2. OP unable to find documentation PEx v2.
