### ISSUE TITLE
V1 editorial review

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/waci-didcomm#24]
### Rebranding

- [x] need to create new github repo waci-didcomm - https://github.com/decentralized-identity/waci-didcomm
- [x] preserve github history - https://github.com/decentralized-identity/waci-didcomm
- [x] publish latest spec - https://identity.foundation/waci-didcomm/
- [x] redirect latest old spec to latest new spec
- [x] archive this repo after moving all issues to the new repo.

### Editorial and Content Review

Review the sections of the spec, address any spelling, grammar or readability mistakes.

**Comment by bumblefudge** [comment]
Ready to close after #12 is merged

**Comment by OR13** [comment]
Closing, tracking remain work in the links above.
