### ISSUE TITLE
Is this line still accurate?

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/waci-didcomm#3]
> This version of the specification also restricts itself to [Verifiable Credentials](https://www.w3.org/TR/vc-data-model/) that make use of [BBS+ LD-Signatures](https://w3c-ccg.github.io/ldp-bbs2020).

I assume so, but:
 - I am unsure of the referent of "this version" - v0.1? v1?
 - perhaps I should go through and change every `specification` to `profile`, where the referent is this work item?

**Comment by brianorwhatever** [comment]
Discussed on call on 04/04/22 and said I would take a stab at this however digging in more there is quite a lot of references to BBS so a wholesale removal is challenging as it's core to the spec. Should we instead change some of the wording to say we are using `JsonWebSignature2020` and `Ed25519Signature2018` with plans for incorporating a new BBS suite in the future?

**Comment by OR13** [comment]
use `JsonWebSignature2020` and `Ed25519Signature2018`... don't leave any references to older bbs+

**Comment by bumblefudge** [comment]
addressed in #12

**Comment by OR13** [comment]
calling this closed.
