### ISSUE TITLE
Changes required for changes to serviceEndpoint in didcomm

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/waci-didcomm#8]
There are some changes happening to serviceEndpoints in didcomm... These changes will need to be reflected in this spec
https://github.com/decentralized-identity/didcomm-messaging/pull/352

**Comment by brentzundel** [comment]
waiting on conversation in DIDComm to settle and add those changes, then we should change our spec to match.

**Comment by rolsonquadras** [comment]
Link to the service property in waci-didcomm spec - https://identity.foundation/waci-didcomm/#service-property

**Comment by OR13** [comment]
Tracking https://github.com/decentralized-identity/didcomm.org/pull/33
